### ISSUE TITLE
Mistakes found

### ISSUE THREAD

**Issue by dkchiem** [Samuel-Martineau/Create-Custom-Command#2]
1. There are many questions in witch you wrote "wich" instead of "which"
2. "Are-you" does not need a "-" it's simply "Are you"

You could possibly do a search and replace to fix this

**Comment by Samuel-Martineau** [comment]
Sorry for that! English is not my first language so I still do some really dumb mistakes... Could you do a PR?

**Comment by Samuel-Martineau** [comment]
Closed by #4
